### ISSUE TITLE
Cannot update project name

### ISSUE THREAD

**Issue by krisrefs** [texterify/texterify#95]
When I'm trying to update the name of a project, then it says all is good, but it does not change.

It seems like it makes the request fine, but is missing a payload.

Not a major problem for me, but it would be nice to get fixed.

Attached screenshot of request (Not it is the standalone docker env. v.1.0.7)

![Untitled](https://user-images.githubusercontent.com/97029892/148787267-307d69e4-37fe-44ec-9bdb-2c387cb4282b.png)
![Untitled1](https://user-images.githubusercontent.com/97029892/148787269-b46b2907-253f-45f5-a641-b0872b6bf73f.png)

**Comment by chrztoph** [comment]
Hey, thanks for the bug report.
This issue has already been fixed in the latest master that is live at [https://app.texterify.com/](https://app.texterify.com/) but there is no on-premise version released for which this issue has been resolved.

It has been fixed in the following commit: https://github.com/texterify/texterify/commit/a1d634ddb5ee7682d002ce2948b7d221678fff02

If you can reproduce it for the cloud [Texterify](https://app.texterify.com) version let me know. 🙂
